### PR TITLE
Pull in all development that has happened in the SV-ROS line

### LINKED ISSUE #12: Merge with the SV-ROS team

### PR DESCRIPTION
**Pull request by rohbotics**
Includes dynamic reconfigure
Larger image buffer 
skip_frames parameter.

Closes #12

### CODE REVIEW

**Comment by rohbotics** [comment]
@girtslinde can you review this please?

**Comment by rohbotics** [comment]
I tested the camera and everything still works :)

I'll wait a little before mergeing, if there are any more comments/issues that come up.

**Comment by rohbotics** [comment]
I think this is ready to merge, so I am going ahead with it.

**Comment by girtslinde** [comment]
Regarding that logging question earlier... I think ROS_ERROR would be enough, since this a driver for ROS. I don't know where that vcos_log_error() goes. If it turns out to be useful for some reason, I imagine there could be a function that calls both.

**Pull request merged**
