### PR TITLE
Add a note about dynamic reconfigure

### PR DESCRIPTION
**Pull request by jim-v**
- In the long term we should have a document about ROS_HOSTNAME and ROS_MASTER_URI to which we can refer.

### CODE REVIEW

**Review by davecrawley — CHANGES_REQUESTED** [review]
Comments like:
" variables on `raspi.local` are set correctly."
Don't have much meaning unless you know what "correctly" is. Better to say

 " variables on `raspi.local` are set to [whatever correct is]" then describe why this is important.

For example you might say

"variables on 'raspi.local' are set to your raspi hostname. This is important as ROS will look for this when operating Raspicam.

**Comment by rohbotics** [comment]
@davecrawley Just a comment on how to do a review.

Review comment on a line by line basis are easier to go through and work on, as well as have discussions about. 

In order to add a comment to a line, click on the blue and white plus icon that shows up when you hover over a line in review mode.

**Comment by jim-v** [comment]
I thought that the sentence following " variables on raspi.local are set correctly." did explain what "correctly" was and why it was necessary, but I've changed it in attempt to be more clear.

**Comment by rohbotics** [comment]
@davecrawley Can you update your review with the new changes, so that we can get this item merged?

**Review by davecrawley — APPROVED** [review]

**Comment by rohbotics** [comment]
@jim-v Please use squash and merge

**Pull request merged**
